default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ig_api_development
  
test:
  <<: *default
  database: ig_api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>